### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by Toma-Bad** [crpurcell/friendlyVRI#4]
Hi everyone,

If i try to run using python3, i get the following error:

 File "vriTk.py", line 115, in <module>
    from matplotlib.backends.backend_tkagg import NavigationToolbar2TkAgg
ImportError: cannot import name 'NavigationToolbar2TkAgg' from 'matplotlib.backends.backend_tkagg'
Cheers,
B

**Comment by masolimano** [comment]
Hi,
I am also having this issue in python 3. I've tried both in a conda environment and in standalone system python.  Then I tried with a python 2.7.15 environment and it worked fine but I received this useful warning:
```
vriTk.py:1285: MatplotlibDeprecationWarning: The NavigationToolbar2TkAgg class was deprecated in version 2.2.
  self.toolbar = MPLnavToolbar(self.figCanvas, self.tbarFrm)
vriTk.py:1437: MatplotlibDeprecationWarning: The FigureCanvasTk.show function was deprecated in version 2.2. Use FigureCanvasTk.draw instead.
  self.figCanvas.show()
```
Hope this helps. If I find some time I could try fixing it and send a PR.
Best,
Manuel

**Comment by crpurcell** [comment]
Now working on python 3.9 after changing to the figCanvas.draw() function.
